# Setup
name:         Chatter Gaily
tagline:      Chatter Gaily on GitHub Pages
baseurl:      "https://chattergaily.github.io"
locale:       "en"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-architect
